definitions:
  pojo.Log:
    properties:
      logId:
        description: 定義json的name是什麼
        type: integer
      logip:
        type: string
      logstatus:
        type: string
      logurl:
        type: string
    type: object
info:
  contact: {}
  description: 可查詢weblog的資訊
  license:
    name: Apache 2.0
  title: weblog API
  version: "1.0"
paths:
  /log/logs:
    get:
      produces:
      - application/json
      responses: {}
      summary: 查詢所有weblog資訊
      tags:
      - Get weblog.查詢
    post:
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/pojo.Log'
      produces:
      - application/json
      responses: {}
      summary: ADD新增
      tags:
      - 新增
  /log/logs/{id}:
    get:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 以Id搜尋welog資訊
      tags:
      - Get weblog.查詢
swagger: "2.0"
